### ISSUE TITLE
カスタムドメインでサーバーにファイルを置く方法の追加

### ISSUE THREAD

**Issue by uakihir0** [bluesky-jp/welcome-bluesky#15]
カスタムドメインのページ: https://bluesky-jp.github.io/welcome-bluesky/docs/walks/custom_domain
参考: https://m.syui.ai/m/62

**Comment by henoya** [comment]
ここ、書きます。
同じページだと長くなりますが、子ページにしますか？

**Comment by uakihir0** [comment]
@henoya 
ありがとうございます！
そうですね、別ページにしたほうがいいかなとは思います。

**Comment by henoya** [comment]
ページ構成はどうしましょう。
- カスタムドメイン親ページ(今の説明とドメイン取るところまで)
  - DNSレコードで登録するページ(今の内容を流用)
  - .well-known ファイルでの登録ページ
という構成でしょうか。

これにサブドメインの場合をそれぞれ加える。

あと、関連してハンドルに使える文字種と長さについての簡単な説明も入れたいですね。

アカウント登録の所に入れますか？

**Comment by uakihir0** [comment]
大丈夫です！ 後からページ構成は長さを見て変える可能性はあるとは思うので、まずは適当でも問題ないです！

**Comment by henoya** [comment]
こんな感じで、分割してみました。

https://github.com/bluesky-jp/welcome-bluesky/compare/henoya/add-custom-domain-without-dns

この後、サブドメインについて追加する予定です。

いったんプルリク出した方がいいでしょうか？

**Comment by uakihir0** [comment]
@henoya
プルリク出すタイミングは自由にしてもらって大丈夫です！
(特にまだ書き途中とかでも全然大丈夫です)
そのタイミングで自分がローカルで確認しようと思います。

**Comment by henoya** [comment]
了解です。

**Comment by henoya** [comment]
#20
プルリク出しました。
